name: Test CI CD Using Github Actions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          run: |
            echo "Host: ${{ secrets.VPS_HOST }}"
            echo "User: ${{ secrets.VPS_USER }}"
